### ISSUE TITLE
Issue with replication yml/training file

### ISSUE THREAD

**Issue by rtaori** [Hadisalman/smoothing-adversarial#2]
Hi,
I downloaded the models from the provided link and am specifically looking at the imagenet models. Are the resnet50 models in the `replication` directory similar to the ones from https://arxiv.org/pdf/1902.02918.pdf? 
If so, is there a reason why the yml file says the 0 noise model was trained with 0.12 noise:
```
jobs:
- name: imagenet/resnet50/noise_0.00
  sku: G4
  sku_count: 1
  command:
  - python code/train.py imagenet resnet50 ./ --batch 256 --workers 16 --noise 0.12
  id: application_1554838020656_3420
```
If the model was trained with 0.12 noise, could one with 0.00 noise be provided?
